### ISSUE TITLE
Cannot authenticate using this example with my work's AD

### ISSUE THREAD

**Issue by connelhooley** [Azure-Samples/active-directory-dotnet-native-uwp-v2#2]
I have created/registered an Azure AD application in the Azure portal against my work's AD and I am using its ClientID in this demo app.

Whenever I try and login I enter my work email address and the pop up redirects to my work's log in page. Once I type in my password I am redirected to a blank page with the following error message:

> We can't connect to the service you need right now. Check your network connection or try this again later.

I can successfully log in to the [Graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) with my work email address and then access the Graph API there to access the information I need.

I've tried running Fiddler to find out where the popup is trying to go but Fiddler running stops it from working at all.

Is there anything else I need to do to get the `PublicClientApplication.AcquireTokenAsync` to work with work's AD?

**Comment by jmprieur** [comment]
@connelhooley : did you follow the optional steps 4 in the Readme.md?
If yes, did you work AD admin impose special policies?

**Comment by jmprieur** [comment]
Did you use the Aure portal (https://portal.azure.com)? or the V2 app registration portal? (https://identity.microsoft.com)

**Comment by jbpoulsen** [comment]
I have the exact same issue using an App created in the Azure Portal.

It seem that no matter if set the UseCorporateNetwork or not, i get the above error message. The only way to solve the issue is to run this command in CMD: 
<<<REG ADD "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\authhost.exe" /v EnablePrivateNetwork  /t REG_DWORD /d 1 /f>>>

But that solution is not viable since i cannot expect all my app users, that connect within their corporate network to do this. The issue is only present when i try to authenticate using my corporate network.

**Comment by jmprieur** [comment]
See also https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1032

**Comment by jmprieur** [comment]
@jennyf19 : FYI

**Comment by jennyf19** [comment]
@jbpoulsen @connelhooley 
In the app's `package.appxmanifest` file, you need to add the following capabilities:
``` <Capabilities>
    <Capability Name="internetClient" />
    <Capability Name="privateNetworkClientServer" />
    <uap:Capability Name="enterpriseAuthentication" />
    <uap:Capability Name="sharedUserCertificates" />
```
In order to log-in with a corp account. Please see this section of the wiki for more information on using [UWP with corp network](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows#properties-of-platformparameter-specific-to-winrt-and-uwp-corporate-network).

**Comment by connelhooley** [comment]
I'm afraid I no longer work for the organisation that I was trying to authenticate with so I'm unable to try any of the steps from @jennyf19 or @jmprieur unfortunately.

Sorry about that.
